#!/usr/bin/env python

from __future__ import print_function

from setup_utils import *
import glob

# icat.client
actions, arg, props = getActions()

if arg == "INSTALL":

    try:
        wheels = glob.glob("*.whl")
        if len(wheels) != 1: abort ("There must be exactly one .whl file")
        cmd = "pip install " + wheels[0]
        out, err, rc = actions.execute(cmd)
        if rc: abort(cmd + " -> " + out + err)
        if actions.verbosity:
            print(out)

    except Exception as e:
        abort(str(e))

if arg == "UNINSTALL":

    try:
        cmd = "pip uninstall -y icat"
        out, err, rc = actions.execute(cmd)
        if rc: abort(cmd + " -> " + out + err)
        if actions.verbosity:
            print(out)

    except Exception as e:
        abort(str(e))
